#!/bin/bash
#PBS parameters...

TRINOTATE_HOME=		#Path to Trinotate-3.1.1 directory
SCRIPT=${TRINOTATE_HOME}/admin/Build_Trinotate_Boilerplate_SQLite_db.pl
TAG="00_preparing_db"
OUTPUT_DIRECTORY=	#path to output directory
WORKING_DIRECTORY=${OUTPUT_DIRECTORY}/${TAG}

mkdir -p ${WORKING_DIRECTORY}

cd ${WORKING_DIRECTORY}

$SCRIPT Trinotate	#Once it completes, it will provide to you:	Trinotate.sqlite ; uniprot_sprot.pep ; Pfam-A.hmm.gz

makeblastdb -in uniprot_sprot.pep -dbtype prot

gunzip Pfam-A.hmm.gz

hmmpress Pfam-A.hmm

